server:
  port: 8818
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: 'shopping-search-ms'
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
  data:
    solr:
      host: http://localhost:8080/solr
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

pagehelper:
  helper-dialect: mysql
  reasonable: true

 